### ISSUE TITLE
acompanhamento dos comentários

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#10]
http://logics.emap.fgv.br/wn/synset?id=03151582-a&term=wn30_lexicographerFile:adj.ppl#comment-1786219461

O mecanismo de discussão não está bom, ainda iremos melhorar. Acontece que vários comentários não geram discussão pois são casos triviais.  Nestes casos, eu apenas aplico a mudança sugerida sem responder ao comentário. O ruim é que quem comentou fica sem saber o que foi aceito e se já foi aceito. 

Outros comentários, como o acima, geram alguma dúvida e espaço para discussão. Estes deveriam ser de alguma forma listados como "em aberto" para sabermos o que precisa de resposta ainda.

**Comment by arademaker** [comment]
Outro caso de discussão interessante note que dois synsets acabam sendo referenciados.  Outro problema sério: 

http://logics.emap.fgv.br/wn/synset?id=09921034-n&term=chosen e
http://logics.emap.fgv.br/wn/synset?id=09921034-n

São para o disqus diferentes URLs?! Feio!

**Comment by fcbr** [comment]
Isso, me parece, e' como o DISQUS associa URLs a discussoes.

O "id" da discussao acaba sendo a URL onde o javascript do Disqus e' executado.

**Comment by arademaker** [comment]
sim, é via URL com certeza. Eu já sabia disso, mas como temos mais de uma possível url para as páginas de synset, geram discussões diferentes.  Ou garantimos que todas as páginas de synset só tem uma url possível, ou investimos em alternativas ao disqus já pensando em todas as limitações outras dele...  

ps: nós obviamente pode significar eu dependendo do seu interesse e esforço possível além do combinado.

**Comment by fcbr** [comment]
o parametro "term" foi implementado a pedido para que o termo na busca fosse reutilizado no formulario na pagina do synset.  podemos implementar essa funcionalidade de outra maneira que nao necessite o uso desse parametro no GET (por exemplo, via propriedades de sessao) ou simplesmente remove-la por ora.

**Comment by arademaker** [comment]
É uma idéia que resolve parcialmente a questão. Quando algum filtro das facetas é selecionado este valor também é passado na url? Algum outro caso que permita diferentes parametros de url nas páginas dos synsets? Senão, isto resolve pelo menos um problema agora. 

Se for apicar isso, me avise que eu posso no disqus mudar a URL do comentário.

**Comment by fcbr** [comment]
apenas TERM e' passado; abri a issue #19 para acompanhamento.
