### ISSUE TITLE
Update word_count_pt to also consider suggestions

### ISSUE THREAD

**Issue by fcbr** [fcbr/cl-wnbrowser#111]
This is an alternative to #106 -- right now the word_count_pt counts the number of words in the word_pt field.  The issue is that this field is only updated after the entire "suggestion" -> "vote" -> "commit" cycle is complete, which can take a while.  This issue proposes updating the word_count_pt to consider the additions and removals that are still pending.  This way people can have a better idea of which synsets still need actual work.

**Comment by arademaker** [comment]
It works for me. But we need to make these decisions clear to the users.

**Comment by arademaker** [comment]
In that case, we will be following a path to take the state of the DB as the possible state given the suggestions. I like the approach, but I would suggest a consistent one. In the result of a search, as in http://wnpt.brlcloud.com/wn/search?term=terrorismo, the synsets should be listed considering the suggestions too.

**Comment by fcbr** [comment]
This changed into a different thing (which I agree).  I'll close this one and open a new one with some of the ideas we discussed recently.
