### ISSUE TITLE
sugerir marcação de synset não lexicalizável

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#121]
como diferenciar se um synset anda não foi analisado de um synset que não tem lexicalização em PT? Uma idéia é permitir que pessoas sugiram e votem em uma explicita marcação do synset como não lexicalizado.

**Comment by livyreal** [comment]
concordo que podemos ter um caixinha para marcar isto ou então que funcione como um voto mesmo, via um botão, por exemplo.
por enquanto podemos usar as hashtags também. tenho usado #lack para synsets que já visitei e não têm lexicalização e também para synsets cuja word correspondente em PT não é óbvia (faz parte de uma outra classe gramatical, ou é uma MWE).

**Comment by arademaker** [comment]
correto. o problema das hashtags é que a interface não esta ajudando no reuso delas. Temos hoje uma grande variedade de hashtags redundantes. Vou fechar este ticket porque a melhoria do uso das hashtags já está documentada em #79 #80 #81 e #82
