### ISSUE TITLE
retorno da busca

### ISSUE THREAD

**Issue by livyreal** [fcbr/cl-wnbrowser#124]
quando faço uma busca, por exemplo "song", aparece uma lista de todos os synsets que em algum campo tem a palavra (song como word, song na glosa, etc). gostaria que os resultados da busca viessem listados priorizando o campo "word". assim apareceriam primeiro todos os synsets com a word "song" e depois apareceriam os synsets em que "song" está na glosa ou no exemplo.

**Comment by arademaker** [comment]
Vc pode tentar

http://wnpt.brlcloud.com/wn/search?term=word_en%3Asong

usar no campo busca "word_en:song" sem as aspas!
