### ISSUE TITLE
Deleting votes without refreshing isn't working

### ISSUE THREAD

**Issue by fcbr** [fcbr/cl-wnbrowser#133]
If you vote on a suggestion and then change your mind and click on the opposite vote, it won't be counted.  You need to reload the page and cast the new vote.

**Comment by livyreal** [comment]
este erro parece acontecer mais recorrentemente quando eu acesso do celular

**Comment by fcbr** [comment]
The issue is a bit more general than I previously thought.  When we first cast a vote, we don't update the the HTML element with the vote id that is created by the server.  If delete vote is called in the same session, we don't know the vote id and the delete routine fails.
