### ISSUE TITLE
Listas de palavras

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#135]
Em http://wnpt.brlcloud.com/wn/prototypes/verbs

Mudar URL para algo mais genérico, não estamos mais falando apenas de verbos.

**Comment by vcvpaiva** [comment]
acho que  estamos sim so falando de verbos por enquanto.

**Comment by vcvpaiva** [comment]
Mas gostaria de ver na pagina inicial o numero de synsets que temos pra cada POS, se possivel. no momento eu faco a subtracao dos da PWN. se comecarmos a ter PT synsets, esse metodo nao vai funcionar. 
Tb seria bom ter a query pra lemmas em algum lugar e ter um processo de verificacao da resposta. se POS=verbo, precisamos ter um infinitivo, 'e -ar-er, ir ou -or. ainda temos coisas que nao sao verbos listadas como tal.

**Comment by arademaker** [comment]
vide http://wnpt.brlcloud.com/wn/stats fechando.

**Comment by vcvpaiva** [comment]
Alexandre,

>se POS=verbo, precisamos ter um infinitivo, 'e -ar-er, ir ou -or. ainda temos coisas que nao sao verbos listadas como tal.
isso nao foi resolvido. voce quer que troque o nome do issue?
