### ISSUE TITLE
páginas estáticas

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#14]
como mesclar páginas HTML estáticas ou produzidas por algum static site generator com as partes dinâmicas dentro do mesmo path /wn/ do servidor?

**Comment by fcbr** [comment]
basta coloca-las no diretorio static/ e acessa-las pela URL /wn/st/XXX

isto resolve a sua issue?

**Comment by arademaker** [comment]
Acho que sim, em nosso encontro vc pode me explicar estas coisas ou
documentar de forma simples em algum file no repo? Talvez eu possa mesmo
gerar as páginas via jekyll ou similar. O path tem que ser st ou pode ser
outro?

Ab.,

**Comment by fcbr** [comment]
por exemplo, o arquivo "error.html" aqui:

https://github.com/fcbr/cl-wnbrowser/blob/master/static/error.html

e' acessivel pela URL http://logics.emap.fgv.br/wn/st/error.html

o path /st/ pode ser renomeado, claro.
