### ISSUE TITLE
add logo

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#142]
Vide msg 29/12/2015 Valeria com sugestão de logo.

**Comment by rafaelbetatester** [comment]
Usei https://github.com/own-pt/openWordnet-PT/blob/master/logo/own-b%2Bw.png este logo e coloquei à direita. @vcvpaiva , @livyreal. O logo deve ser apenas no /wn/ ou no /wn/search/ também?

Segue uma pré-visualização: 

![logo2](https://cloud.githubusercontent.com/assets/11369578/14897777/c832aff2-0d59-11e6-99e2-f07710021170.png)

**Comment by vcvpaiva** [comment]
Obrigada por colocar o logo @rafaelbetatester . acho que deve aparecer tanto no /wn/ quanto no/wn/search/

**Comment by livyreal** [comment]
concordo que pode aparecer nas duas, e tenho duas sugestões.
1. O logo na página inicial pode seguir o mesmo padrão da frase "welcome to Openwordnet-pt, an open Portuguese wordnet. Isto é, ter este espaçamento mínimo entre o "pt" da logo e a borda direita da página; o "openwordnet" do logo alinhado com esta frase e do mesmo tamanho.
2. na página de synsets, por exemplo [casa](http://wnpt.brlcloud.com/wn/synset?id=07971449-n), o link para a página inicial poderia ser o logo. Assim sempre que alguém fizer um print de um synset, vai ter o logo.

O que vcs acham?

**Comment by arademaker** [comment]
@rafaelbetatester me avise quando chegar na IBM que concluímos este assunto juntos.

**Comment by arademaker** [comment]
Os logos estão aqui https://github.com/own-pt/openWordnet-PT/tree/master/logo

**Comment by arademaker** [comment]
closed by 7441b1719fd446a4299c49e359f17b0dd615a3a9. @fcbr pode fazer o deploy.

**Comment by rafaelbetatester** [comment]
Atualizar theme.css também.

**Comment by arademaker** [comment]
@rafaelbetatester não entendi seu comentário. Pode ser mais preciso? Faltou algum arquivo? Faltou atualizar no repo ou no deploy do servidor feito pelo @fcbr ?!

**Comment by vcvpaiva** [comment]
@rafaelbetatester eu acho que ficaria mais bonito se um logo fosse um pouco menor nas paginas de pesquisa. e' facil de mudar?

**Comment by rafaelbetatester** [comment]
O tamanho está sendo ajustado no theme.css. O arquivo foi atualizado no pull. No deploy que não foi atualizado o .css, foram atualizados apenas os templates. No theme.css também colocamos as margens em tudo, etc.

**Comment by fcbr** [comment]
este problema e' conhecido -- voce tem que limpar seu cache.  cf. #66

**Comment by rafaelbetatester** [comment]
Ok, Resolvido.

**Comment by rafaelbetatester** [comment]
Ok, era esse meu problema.

**Comment by livyreal** [comment]
obrigada pelo trabalho @rafaelbetatester , mas acho que (ainda) não ficou bom onde está não. a página "começar" com o box do search não fica legal.
