### ISSUE TITLE
Bug: search for *ão, 

### ISSUE THREAD

**Issue by vcvpaiva** [fcbr/cl-wnbrowser#146]
Bug: search for *ão, choose verb synsets, have 460 results, not a single one in the first 10 terminates in -ão. have two good ones in the second ten results. why?

**Comment by arademaker** [comment]
this was already documented. you have to use regex search

http://wnpt.brlcloud.com/wn/search?term=word_pt%3A%2F.*ão%2F&start=0&limit=10&fq_rdftype=VerbSynset

See the docs in https://github.com/own-pt/openWordnet-PT/wiki/How-to-use
