### ISSUE TITLE
Two votes and not committed in the last batch

### ISSUE THREAD

**Issue by vcvpaiva** [fcbr/cl-wnbrowser#149]
The examples are
http://wnpt.brlcloud.com/wn/synset?id=01804595-v (bajular) and
http://wnpt.brlcloud.com/wn/synset?id=01801697-v
there might be others in the emotion 30 verbs that Livy and I have gone over.
Thanks

**Comment by fcbr** [comment]
I have just identified the issue: the issue only got two votes on january 30, which was after the last round of approvals.  On the next round, these will be committed.
