### ISSUE TITLE
issue when navigating filtered list of results

### ISSUE THREAD

**Issue by fcbr** [fcbr/cl-wnbrowser#15]
eu quero saber todos os motion.verbs (1408 results found for 'wn30_lexicographerFile:verb.motion)
que sao  core synsets, sao 114 deles.

wn30:CoreConcept (114)

eu clico no link e vejo os 10 primeiros. mas quando eu sou pro next, pra ver os proximos 10, ate' chegar nos 114, a busca volta pra TODOS os

1408 results found for 'wn30_lexicographerFile:verb.motion'

me parece, em vez de continuar procurando pelos 114 core e motion.

**Comment by vcvpaiva** [comment]
excellent, managed to get to the end of motion verbs that are core synsets.

On Wed, Jan 14, 2015 at 6:44 AM, Fabricio Rosario notifications@github.com
wrote:

> Closed #15 https://github.com/fcbr/cl-wnbrowser/issues/15 via ea364f0
> https://github.com/fcbr/cl-wnbrowser/commit/ea364f0bb5ecb058a6ebd65156ebeba6579b6955
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/15#event-218774427.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/

**Comment by fcbr** [comment]
new faceted search broke this again.

**Comment by vcvpaiva** [comment]
muito bom!

On Tue, Jan 20, 2015 at 10:23 AM, Fabricio Rosario <notifications@github.com

> wrote:
> 
> Closed #15 https://github.com/fcbr/cl-wnbrowser/issues/15 via 76b57e0
> https://github.com/fcbr/cl-wnbrowser/commit/76b57e0a9cd43bee01f4de052178dd1f5e7f2f26
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/15#event-221791236.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/
