### ISSUE TITLE
Switch to Elastic Search?

### ISSUE THREAD

**Issue by fcbr** [fcbr/cl-wnbrowser#152]
Elastic Search seems to be a better alternative to SOLR, especially when it comes to aggregation.  We can also implement "virtual" fields that are computed on the fly, something that we are doing manually on SOLR these days (things like sum of votes, number of words, etc.)

This issue discusses whether we want to switch to ES or not and the planning associated with it.

**Comment by arademaker** [comment]
escolhemos apostar em um backend mais estruturado: triplestore ou graph database. fechando este issue.
