### ISSUE TITLE
missing #

### ISSUE THREAD

**Issue by livyreal** [fcbr/cl-wnbrowser#155]
some of hashtags that we have are not listed on "activity" pages.

I used #pair10 here http://wnpt.brlcloud.com/wn/synset?id=01722815-v
but this hashtag is not listed, therefore I cannot find the synset which I think should be merged with this one.

**Comment by arademaker** [comment]
@livyreal ok, it is a bug. But... 

First, the hashtags are not working as expected, I am not sure if we will keep them. Second, I have already asked to substitute these idea of pairXX with a canonical hashtag with an argument for making furture processing easier. I suggested #sameas:XXXXXX. With that, you can also have a list of pairs:

http://wnpt.brlcloud.com/wn/search-activities?sf=&so=&term=&start=0&fq_tag=HASHsameas

I would like to close this issue, ok?

**Comment by arademaker** [comment]
See https://github.com/own-pt/openWordnet-PT/wiki/Hashtags

**Comment by livyreal** [comment]
I first used #pair, and then, when you decided that we should use #sameas, I changed, but I did not have time to change all of them to your new way of track them. I'm completely against not using hashtags, as they are really useful to me and Valeria.

this wiki has nothing to do with this issue, but you can close everything you want.
