### ISSUE TITLE
link de synset para nominalizações

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#16]
http://logics.emap.fgv.br/wn/search?term=excluir

quando na página de um synset que entre suas palavras tem alguma que é parte de uma nominalização, precisamos ter link para a nominalização.

**Comment by vcvpaiva** [comment]
excelente!

On Wed, Jan 14, 2015 at 2:30 PM, Fabricio Rosario notifications@github.com
wrote:

> Closed #16 https://github.com/fcbr/cl-wnbrowser/issues/16 via 0de0b31
> https://github.com/fcbr/cl-wnbrowser/commit/0de0b31bb49b996715598734406b9dda0e943add
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/16#event-219080343.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/
