### ISSUE TITLE
Compare coverage with Dicionario Creativo

### ISSUE THREAD

**Issue by vcvpaiva** [fcbr/cl-wnbrowser#161]
Gostariamos de saber se temos cobertura semelhante ao dicionario criativo
http://dicionariocriativo.com.br/
o Pedro Balage, aluno do Thiago Pardo,  http://pedrobalage.com/ e' o pesquisador envolvido,
http://dicionariocriativo.com.br/saiba-mais

**Comment by arademaker** [comment]
this is not an interface issue.
