### ISSUE TITLE
morphosemantic links in -er and professions

### ISSUE THREAD

**Issue by vcvpaiva** [fcbr/cl-wnbrowser#163]
Alexandre has a list of PWN  professions/occupations. maybe we can use morpholinks to help ground these in SUMO?
I'm think of occupations such as welder, carver, singer, etc

**Comment by arademaker** [comment]
isto não é um issue da interface cl-wnbrowser.

**Comment by vcvpaiva** [comment]
>isto não é um issue da interface cl-wnbrowser.

concordo plenamente, mas os outros issues of data estavam nesse diretorio.
