### ISSUE TITLE
how many synsets in PWN have definitions? how many have examples?

### ISSUE THREAD

**Issue by vcvpaiva** [fcbr/cl-wnbrowser#164]
the proposal is to download wicionario and try to complete the intersetion of OWN-PT and wicionario, as described in 
Verena Henrich, Erhard Hinrichs, and Tatiana Vodolazova: Semi-Automatic Extension of GermaNet with Sense Definitions from Wiktionary. In Proceedings of 5th Language & Technology Conference (LTC 2011), Poznań, Poland, November 2011, pp. 126-130.
[[http://www.sfs.uni-tuebingen.de/GermaNet/documents/publications/Henrich-et-al-2011_GermaNet-Wiktionary-Mapping.pdf]](url))

**Comment by arademaker** [comment]
this is not a cl-wnbrowser issue.
