### ISSUE TITLE
Text disappearign from entries?

### ISSUE THREAD

**Issue by vcvpaiva** [fcbr/cl-wnbrowser#170]
Please check http://wnpt.brlcloud.com/wn/synset?id=00542120-v.
it looks like there is a limit to the number of items in  entry now?
some text that I could see before (like a bad gloss) disappeared when I entered more suggestions of translations.

**Comment by fcbr** [comment]
I don't see anything missing from the gloss, so maybe it is a layout issue?  can you post screenshots?

**Comment by vcvpaiva** [comment]
Sure, but the text that was there disappeared. notice how there is only 2 cst suggestions, the rest is all me? there was a gloss and some watson suggestions that I cannot see anymore. what I see is this screenshot
<img width="903" alt="disappearingcome" src="https://cloud.githubusercontent.com/assets/1154463/14942392/93d11294-0f70-11e6-968c-fde67986b2f4.png">

**Comment by vcvpaiva** [comment]
@fcbr teve realmente uma mudanca e agora so' aparecem dez links pra cada entrada. nao sei o que acontece com as outras entradas, nao achei boa essa mudanca nao.

**Comment by fcbr** [comment]
OK, I think I understand the problem, it is related to the way we query SOLR for suggestions.  It is probably adding a limit on the number of search results by default.  Looking into it.
