### ISSUE TITLE
repeated suggestions

### ISSUE THREAD

**Issue by livyreal** [fcbr/cl-wnbrowser#172]
http://wnpt.brlcloud.com/wn/synset?id=00542120-v admitiu duas sugestões iguais (add-word-pt    - começar)

**Comment by arademaker** [comment]
apaguei a sugestão repetida. Este erro já havia sido resolvido, parece que o problema está novamente acontecendo em situações particulares. Vamos monitorar.

**Comment by vcvpaiva** [comment]
it's worth remembering that that the same "word form" in different places of the hierarchy can be actually a different word, given that a word is not simply its form but also its hypo/hypernyms/meronyms etc..
