### ISSUE TITLE
guidelines to add new candidates

### ISSUE THREAD

**Issue by livyreal** [fcbr/cl-wnbrowser#185]
a non-ending discussion is the criteria used to add a given lemma to wordnets in general. Besides complex issues (as pronominal verbs and mwes) that we are still investigating, very basic instructions (and/or linguistic tests, as replacement in context) could be added to the page (or to the readme) to guide new users when adding new candidates for a synset.

We had some discussion on this matter when doing "Extending Adverbial Coverage of OWN-PT", SRW, PROPOR 2018. Need to write down this discussion and make sure all OWN-PT team agrees with the used criteria.

**Comment by arademaker** [comment]
I believe the only robust method is corpus driven. I don’t think we are doing right suggesting world in the WN interface without providing  an example. Moreover, annotated texts could be a by-product of WN expansion

**Comment by arademaker** [comment]
Anyway, this is not and issue about the interface. Please open an issue in the main own-pt repo.
