### ISSUE TITLE
adding suggestions

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#192]
do not reload the page! I need to reload to see the suggestion in the table.

**Comment by arademaker** [comment]
maybe we can avoid the table to make the suggestions appear inline... with some sign to diff them for the `facts`

**Comment by hmuniz** [comment]
Setting the `refresh` parameter to `wait_for` solves the problem. See https://www.elastic.co/guide/en/elasticsearch/reference/6.4/docs-refresh.html
