### ISSUE TITLE
blank search for all

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#196]
http://wn.mybluemix.net/search?search_field=all&term=

it used to work with SOLR. How to browse in ALL documents?

**Comment by hmuniz** [comment]
The blank search is working for another search field such as `word_en`(http://localhost:8040/search?search_field=word_en&term=) but not work for the `all` option is a bug. I am going to fix that.

**Comment by hmuniz** [comment]
Can we close this issue?

**Comment by arademaker** [comment]
yep.
