### ISSUE TITLE
links para outros resources

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#2]
1. SUMO
2. Francis Bond http://compling.hss.ntu.edu.sg/omw/

**Comment by fcbr** [comment]
Parece que voce consertou isso com as ultimas versoes da homepage.  Se entendi errado, por favor reabra.

**Comment by arademaker** [comment]
não exatamente. os links seriam por objetos (senses ou synset). Não consigo reabrir o issue.

**Comment by vcvpaiva** [comment]
otimo, exatamente o que eu pedi, pois nao tinha me dado conta desse repo de bugs/enhacements.

**Comment by fcbr** [comment]
implementado link para OWM.  Preciso de mais informacoes de como linkar para SUMO para poder fechar essa issue.

**Comment by vcvpaiva** [comment]
Oba!! Obrigada.

**Comment by vcvpaiva** [comment]
Acho que o link pra OMWN e' suficiente  pois  ja' da' pra um ser humana a capacidade de verificar o conceito ontologico. Tb fico achando q se fizermos um link separado pra SUMO vamos ter o problema de fLta de sincronizacao com o Bond.
