### ISSUE TITLE
format synset template

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#20]
http://logics.emap.fgv.br/wn/synset?id=01138523-v

Valeria confundiu glossa com palavras. Tornar mais explícito talvez...

**Comment by fcbr** [comment]
alguma sugestao?  talvez por a glosa debaixo das palavras com uma UL/LI ?  (mas temos que pensar no caso de nao termos palavras em PT.)

**Comment by vcvpaiva** [comment]
Valeria nao confundiu palvras com glosas. Valeria achou que nao podiamos
ter glosas, qto mais glosas sem palavras. acho que isso nao 'e importante.

On Thu, Jan 15, 2015 at 3:42 PM, Fabricio Rosario notifications@github.com
wrote:

> alguma sugestao? talvez por a glosa debaixo das palavras com uma UL/LI ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/20#issuecomment-70184364.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/
