### ISSUE TITLE
Use HTTP basic authentication

### ISSUE THREAD

**Issue by hmuniz** [fcbr/cl-wnbrowser#205]
> GitHub is deprecating authentication to the GitHub API using query parameters, such as using a access_token query parameter for OAuth user authentication or a client_id/client_secret query parameter for OAuth application authentication. All authentication to the GitHub API should be done using HTTP basic authentication.

See: https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters

**Comment by hmuniz** [comment]
ed45aabc61fce36ea0d6746d2020af436206c273 use the Authorization HTTP header instead as using the `access_token`  query parameter as suggested.

**Comment by arademaker** [comment]
So simple?! Thank you.

**Comment by hmuniz** [comment]
I think so. If you receive another e-mail about this issue reopen it, please.

**Comment by arademaker** [comment]
Is it solved and pushed to master?

**Comment by hmuniz** [comment]
Yes.
