### ISSUE TITLE
un-escape SOLR special chars

### ISSUE THREAD

**Issue by fcbr** [fcbr/cl-wnbrowser#22]
http://logics.emap.fgv.br/wn/search?term=andar&fq=rdf_type:wn30\:NounSynset

the header should read "7 results found for 'andar' / rdf_type:wn30:NounSynset" instead of the current "7 results found for 'andar' / rdf_type:wn30\:NounSynset"

**Comment by arademaker** [comment]
uma outra forma de deixar isso mais bonito é renomear os valores do banco. Os dois-pontos são problema para o SOLR porque ele usar como separador entre campo e valor. Se eu evitar o wn30:NounSynset e transformar em NounSynset apenas, teremos uma leitura mais clean na interface. Acho que posso resolver isso com os dados diretamente.

**Comment by vcvpaiva** [comment]
hmm esses resultados nao sao pra andar, mas pra "walk", veja que o ultimo
resultado nao tem "andar" nenhum..

On Thu, Jan 15, 2015 at 3:41 PM, Fabricio Rosario notifications@github.com
wrote:

> http://logics.emap.fgv.br/wn/search?term=andar&fq=rdf_type:wn30\:NounSynset
> 
> the header should read "7 results found for 'andar' /
> rdf_type:wn30:NounSynset" instead of the current "7 results found for
> 'andar' / rdf_type:wn30:NounSynset"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/22.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/

**Comment by fcbr** [comment]
vou esperar voce fazer esta atualizacao no SOLR entao para fechar a issue. acho que nao vai precisar alterar nada no codigo.
