### ISSUE TITLE
count of words

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#24]
Será que conseguimos pesquisar e facetar por count of words PT e EN? Ou temos que explicitamente criar um campo nos docs com estes valores? Seria bem legal poder filtrar synsets por números de palavras (usando possívelmente os filtros from faixas (range facets).

**Comment by arademaker** [comment]
Adicionei dois novos campos no schema do solr word_count_pt e word_count_en, respectivamente com a quantidade de palavras (tamanho da lista dos respectivos campos word_pt e word_en). 

Resta agora na interface fazer a facetação por estes campos também.

**Comment by vcvpaiva** [comment]
bug when going back in the new search, it says document expired instead of
going to previous page.

On Fri, Jan 23, 2015 at 1:10 PM, Fabricio Rosario notifications@github.com
wrote:

> Closed #24 https://github.com/fcbr/cl-wnbrowser/issues/24 via 0c2c8cf
> https://github.com/fcbr/cl-wnbrowser/commit/0c2c8cf9908962d07862b43e555cbe7f028dcaa0
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/24#event-223972747.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/

**Comment by fcbr** [comment]
Issue #25 opened.
