### ISSUE TITLE
support for back to search from a synset page

### ISSUE THREAD

**Issue by fcbr** [fcbr/cl-wnbrowser#25]
"search doesn't allow you to go back one page, so if I wan to check all 9 adj pertainnyms and I've seen the first one, I cannot see the other 8, as the document is expired , so the search has to start from the top again."

**Comment by arademaker** [comment]
Valeria, not clear for me. how are you going back?  it is working for me.

**Comment by vcvpaiva** [comment]
Fabricio, obrigada por consertar o problema! so' nao estou entendendo porque o github nao acha que eu contribuo nesse projeto. voce sabe por que?
