### ISSUE TITLE
apresentação de palavras

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#26]
Em http://logics.emap.fgv.br/wn/synset?id=00627824-v

como diferenciar separação de palavras de quando tivermos vírgula dentro de uma "palavra". Na realidade temos itens lexicais, não palavras. E podemos ter, por erros introduzidos, itens com virgula para serem limpos.

**Comment by fcbr** [comment]
talvez um separador menos usado?  tipo o de equivalencia? (&equiv;) ou algum mais grafico (&sdot;)  ?

**Comment by vcvpaiva** [comment]
um outro exemplo de erro desse tipo e' "nem aqui, nem na China" que esta'
parecendo com duas expressoes..
mas acho que igualdade e ponto nao funcionam bem como separadores nao.

2015-01-24 9:21 GMT-08:00 Alexandre Rademaker notifications@github.com:

> Em http://logics.emap.fgv.br/wn/synset?id=00627824-v
> 
> como diferenciar separação de palavras de quando tivermos vírgula dentro
> de uma "palavra". Na realidade temos itens lexicais, não palavras. E
> podemos ter, por erros introduzidos, itens com virgula para serem limpos.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/26.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/

**Comment by arademaker** [comment]
1) podemos usar cores e então as virgulas entre entradas se destacariam; (2) sua segunda sugestão; (3) envolver as entradas com [....] ou "...". Difícil dizer o que fica melhor sem ver os dados...

**Comment by vcvpaiva** [comment]
acho q funcionou bem sim ,o ponto gordinho.

On Wed, Jan 28, 2015 at 5:20 AM, Fabricio Rosario notifications@github.com
wrote:

> Closed #26 https://github.com/fcbr/cl-wnbrowser/issues/26 via 5f2e071
> https://github.com/fcbr/cl-wnbrowser/commit/5f2e071c3947b7bccd8a62b9f2cd9c77195b7c67
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/26#event-226060411.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/
