### ISSUE TITLE
link to SUMO

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#29]
queremos links diretos para SUMO, assim como Francis faz. Mas podemos melhorar a idéia e export também os tipos de links para permitir facetas nestes tipos.

**Comment by arademaker** [comment]
Link http://sigma-01.cim3.net:8080/sigma/WordNet.jsp?synset=200332672&kb=SUMO&flang=SUO-KIF&lang=EnglishLanguage&kb=SUMO

**Comment by fcbr** [comment]
temos que entender o ID do synset direito.  No link acima, esta' "200332672", mas na WN, ele esta' "00332672-v".

**Comment by arademaker** [comment]
SUMO has synset pages:

[1] http://sigma-01.cim3.net:8080/sigma/WordNet.jsp?synset=103545150&kb=SUMO&flang=SUO-KIF&lang=EnglishLanguage&kb=SUMO

I am planning to link our synset page [2] to your synset page [1] so I don't have to worry about the mappings. The users would navigate to concepts only after reach your side. Does it work for you? 

[2] http://logics.emap.fgv.br/wn/synset?id=03545150-n

I need only to confirm how you construct your synset ids. It looks like the prefix 1 is for nouns, 2 for verbs, 3 for adjectives and 4 for adverbs. That is, my suffix "-n" is your prefix 1:

03545150-n => 103545150

am I right?

**Comment by arademaker** [comment]
SUMO has synset pages:

[1]
http://sigma-01.cim3.net:8080/sigma/WordNet.jsp?synset=103545150&kb=SUMO&flang=SUO-KIF&lang=EnglishLanguage&kb=SUMO

I am planning to link our synset page [2] to your synset page [1] so I
don't have to worry about the mappings. The users would navigate to
concepts only after reach your side. Does it work for you?

> > sounds good

[2] http://logics.emap.fgv.br/wn/synset?id=03545150-n

I need only to confirm how you construct your synset ids. It looks like
the prefix 1 is for nouns, 2 for verbs, 3 for adjectives and 4 for
adverbs. That is, my suffix "-n" is your prefix 1:

03545150-n => 103545150

am I right?

> > yes
