### ISSUE TITLE
incorporar nos comentários #hastag e @userid

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#35]
para facilitar comunicação e referências das pessoas. Elas seriam forma de faciltiar a busca nos comentários e "marcar" synsets.

**Comment by fcbr** [comment]
juntando o comentario do issue #58 

Pena que quando
busco por um synset muito específico (especialmente significados que
eu nunca ouvi falar) nem o linguee nem as outras wordnets têm me
ajudado a achar um equivalente, como em
http://logics.emap.fgv.br/wn/synset?id=04119892-n

Acho que vale fazer um comentário neste synset; este poderia receber algo como #dificil para nos chamar atenção para verificação futura.

**Comment by vcvpaiva** [comment]
Fabricio, closed porque vc implementou? ou nao?
sou contra um label "dificil" mas sou a favor de um "later".
valeria

On Tue, Apr 28, 2015 at 6:08 AM, Fabricio Rosario notifications@github.com
wrote:

> Closed #35 https://github.com/fcbr/cl-wnbrowser/issues/35 via d500c9c
> https://github.com/fcbr/cl-wnbrowser/commit/d500c9ca27add290aeca5dbc9b75cffba03ebc42
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/35#event-291948906.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/

**Comment by fcbr** [comment]
Qualquer um ja' pode colocar at-mentions e hash-tags nos comentarios. Eu
acrescentei a possibilidade de buscar por eles agora.

(Pelo menos foi isso que eu entendi deste pedido de enhancement.)

**Comment by arademaker** [comment]
@vcvpaiva a idéia a termos mecanismos parecidos com twitter para achar comentários. Não estamos implementando hashtags específicas, apenas um mecanismo de filtro baseado em hashtags e at-mentions livres. 

Vi agora http://logics.emap.fgv.br/wn/search-activities?term=params:@arademaker mas não parece estar funcionando. O segundo comentário não tem nenhum @arademaker

Também precisamos de coisas mais sofisticadas que irão ser mais demoradas mas que somadas darão realmente a funcionalidade que buscamos.
1. auto-complete de hashtags e at-mentions (como ocorre aqui no github).
2. documentar como as pessoas podem buscar por estas coisas.
3. links na apresentação de hashtags e at-mentions (como esta http://logics.emap.fgv.br/wn/synset?id=14066492-n)
4. Navegação pelas hashtags e at-mentions existentes e caixa de trends de hashtags. 

Enfim, são tentativas de colocar na interface mais recursos para ajudar na nossa comunicação e trabalho colaborativo de revisão. Pode ser que implementar isto tudo não seja nossa prioridade, no entanto.
