### ISSUE TITLE
votação up/down de sugestões

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#36]
idéias de:
https://news.ycombinator.com
http://www.reddit.com/r/lisp/
http://www.quora.com

**Comment by fcbr** [comment]
incorporando comentarios do issue #57 

acho que não tem nada demais em perdermos algumas coisas, mas se esperássemos o sistema de votação/like ficar pronto não teríamos este problema. O Alexandre poderia adicionar um comentário da Valeria que ele não concorda e não votar no comentário... assim esta sugestão que ele rejeita teria um único voto e não dois. Se fizermos assim, temos que combinar que quem fez a sugestão no Disqus não pode votar nela mesma na nova interface, por que o fato do comentário já estar na interface conta como seu voto. Tomando como exemplo este synset, Alexandre poderia adicionar todos os comentários da Valéria ('perceber' e 'ouvir'), poderia votar no 'ouvir' (e não votar no 'perceber'), e Valéria não poderia votar em nada, só na nova opção trazida pelo Alexandre ("entender"). Parece que vai dar trabalho, mas é só bater o olho nas sugestões importadas para saber quem de nós a deu e tomar cuidado para não votarmos repetidamente. Faz sentido?
Faz sentido termos mais recursos na interface para evitar votos ou sugestões duplicadas. 

Para este passivo dos comentários, também podemos ver se seria possível que algumas contas pudessem se logar como outras apenas para que as sugestões ficassem registradas com a autoria correta.
