### ISSUE TITLE
bug na busca de atividades

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#43]
http://logics.emap.fgv.br/wn/search-activities

Temos um bug na marcação dos filtros. Parece estar funcionando com um OR e não um AND. Veja escolhendo add-example e depois new. Ou um usuário e depois apenas comentários.

**Comment by fcbr** [comment]
o mesmo acontece para busca de palavras.  apenas um dos filtros esta' sendo aplicado, nao todos.

**Comment by fcbr** [comment]
O bug era no lado da API no Bluemix.  Fixed.
