### ISSUE TITLE
aumentar campos de glossa e exemplo

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#46]
Os campos de glossas e exemplos precisam ser redimencionáveis e serem maiores para textos mais longos.

**Comment by fcbr** [comment]
Aumentei os campos, mas para coloca-los redimensionaveis teriamos que usar o textarea, que permite line breaks, o que nao sei se e' uma coisa que queremos.  Se nao tiver problema, posso mudar.

**Comment by arademaker** [comment]
podemos ficar como está mas também poderíamos ter um pós-processamento dando conta das quebras de linha. Mas por agora acho que temos outras prioridades.
