### ISSUE TITLE
atualização da lista de atividades

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#47]
Após sugestão ser aceita, na lista de atividades ela ainda é new:

Vide sugestao elianemart
- http://logics.emap.fgv.br/wn/synset?id=08626758-n e
- http://logics.emap.fgv.br/wn/search-activities?term=&start=0&bookmark=&fq_user=%28elianemart%29

**Comment by fcbr** [comment]
na verdade, e' o status do comentario e' que e' "new".  o segundo link que voce enviou lista apenas o comentario.
