### ISSUE TITLE
busca por synset

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#5]
implementar alguma forma de busca por synset mais intuitiva. A opção  agora seria digitar o código do synset na url diretamente que retorna a página do synset.

**Comment by fcbr** [comment]
Isso e' resolvido acrescentando a seguinte linha no schema do SOLR e reindexando a base toda.

  < copyField source="id"  dest="text"/ >

Teria como voce fazer isso?

**Comment by arademaker** [comment]
ok. para a aplicação, tem algum problema eu usar o campo word_pt ao inves de word_br?

**Comment by fcbr** [comment]
Existe um lugar no codigo que assumimos word_br.  Assim que voce mudar,
me avise para eu atualizar o codigo.

**Comment by arademaker** [comment]
já mudei.

**Comment by fcbr** [comment]
OK, ja' atualizei o site.

**Comment by arademaker** [comment]
Só não entendi por que solr parou de quebrar o id no hífen como parecia estar fazendo antes... =

**Comment by fcbr** [comment]
Nao parou (veja o debug da execucao da query), mas os documentos que tem o match 100% vao para o topo da lista.

**Comment by arademaker** [comment]
entendi. Bem, então o issue não está propriamente resolvido, né? Agora vi, busca por 08222966-n devolve 82K docs.  Acho que o comportamento ideal seria similar ao do http://compling.hss.ntu.edu.sg/omw/cgi-bin/wn-gridx.cgi?gridmode=grid que quando recebe um ID mostra o synset direto.

**Comment by fcbr** [comment]
se voce colocar o synset id entre aspas ele retorna so' um resultado, mas eu reabri pra pensarmos na usabilidade.  talvez um help ajude ou uma busca especializada / inteligente.
