### ISSUE TITLE
novo erro com buscas sequenciais

### ISSUE THREAD

**Issue by vcvpaiva** [fcbr/cl-wnbrowser#51]
Fabricio,
se eu peco todos os synsets usando
'_:_' e depois todos os verbos
VerbSynset (13767)
eu vejo que temos
BaseConcept (1441)
CoreConcept (996)
mas qdo peco pra ver ou os coresynsets ou os basesynsets vejo essa mensagem de erro:

Error

The search for '_:_' resulted in the following error:

```
dimension 'rdf_type' was already added
```

Tambem tenho problemas se tento fazer o contrario, primeiro pedir os coresynsets

CoreConcept (4960)

mas quando tento clicar no

VerbSynset (996)
o mesmo erro aparece

obrigada por investigar,
valeria

**Comment by fcbr** [comment]
Vou abrir um support case para o Cloudant.

EDIT: caso aberto, numero 46230.

**Comment by vcvpaiva** [comment]
thanks!

On Tue, Apr 14, 2015 at 1:08 PM, Fabricio Rosario notifications@github.com
wrote:

> Vou abrir um support case para o Cloudant.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/51#issuecomment-93044269.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/

**Comment by fcbr** [comment]
OK, implementei um workaround.  Vou deixar essa issue aberta caso o pessoal da Cloudant responda com a maneira correta de fazer isso.  Vou mudar para enhancement ja' que o bug foi consertado, mas provavelmente nao da maneira correta.

**Comment by fcbr** [comment]
switching to bug.  We still have issues with RDF Types that have single values (i.e., are not arrays).

**Comment by fcbr** [comment]
the workaround was fixed in Cloudant.  Changing back to enhancement.

**Comment by fcbr** [comment]
Resposta do Cloudant.  Teremos essa funcionalidade no futuro.  Como somente resta o nosso workaround, vou fechar a issue.

"Thanks for emailing Cloudant Support. I was able to reproduce your issue and confirmed with our Search developers that it is not currently possible to use multiple "drilldown" parameters to the same field name. However, this functionality is under development and will eventually be included in our core software."
