### ISSUE TITLE
avaliar anotação de corpus

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#56]
Como disse para Claudia, acho a idéia de termos alguns revisores avaliando os resultados de FreeLing boa. O negócio apenas é pensar em uma boa interface para recolher as avaliações dos revisores. 

Por exemplo, a sentença: 

```
$ cat teste3.text
Os poloneses acreditam no futuro da batata, cuja produção no país já supera 40 milhões de toneladas ao ano.
```

Analisada por FreeLing, devolve:

```
$ cat lixo.text
Os o DA0MP0 0.960449 -
poloneses polonês AQ0MP0 1 02961258-a:0
acreditam acreditar VMIP3P0 1 00683280-v:0
em em SPS00 1 -
o o DA0MS0 1 -
futuro futuro NCMS000 0.819742 03408721-n:0/06330401-n:0/15121625-n:0/15263795-n:0
de de SPS00 1 -
a o DA0FS0 0.676943 - a SPS00 0.311806 - o PP3FSA00 0.00614912 - o PD0FS000 0.00498492 - a NCMS000 0.000116421 -
batata batata NCFS000 1 12897493-n:0
, , Fc 1 -
cuja cujo PR0FS000 1 -
produção produção NCFS000 1 00912960-n:0/00913705-n:0/03287178-n:0/03841417-n:0/03860882-n:0/04007894-n:0/04612722-n:0/06613686-n:0/07006951-n:0/13758745-n:0
em em SPS00 1 -
o o DA0MS0 1 -
país país NCMS000 1 08168978-n:0/08544813-n:0/08552138-n:0/08654360-n:0
já já RG 0.99556 00031798-r:0/00033922-r:0
supera superar VMIP3S0 0.916667 01101913-v:0/01104018-v:0/01105639-v:0/01106864-v:0/01107544-v:0/01108148-v:0/01108627-v:0/01109259-v:0/01154957-v:0/02619924-v:0/02669081-v:0
40_milhões 40000000 Z 1 -
de de SPS00 1 -
toneladas tonelada NCFP000 1 13721387-n:0/13721529-n:0/13725588-n:0
a a SPS00 1 -
o o DA0MS0 0.946534 - o PD0MS000 0.0337339 - o PP3MSA00 0.0197186 - o NCMS000 1.38766e-05 -
ano ano NCMS000 1 08238660-n:0/15153787-n:0/15201505-n:0/15202634-n:0/15202806-n:0/15203229-n:0/15203565-n:0/15203791-n:0/15204297-n:0/15273626-n:0
```

Se filtrarmos apenas NC:

```
$ awk '$3 ~ /^NC/ {print}' lixo.text
futuro futuro NCMS000 0.819742 03408721-n:0/06330401-n:0/15121625-n:0/15263795-n:0
batata batata NCFS000 1 12897493-n:0
produção produção NCFS000 1 00912960-n:0/00913705-n:0/03287178-n:0/03841417-n:0/03860882-n:0/04007894-n:0/04612722-n:0/06613686-n:0/07006951-n:0/13758745-n:0
país país NCMS000 1 08168978-n:0/08544813-n:0/08552138-n:0/08654360-n:0
toneladas tonelada NCFP000 1 13721387-n:0/13721529-n:0/13725588-n:0
ano ano NCMS000 1 08238660-n:0/15153787-n:0/15201505-n:0/15202634-n:0/15202806-n:0/15203229-n:0/15203565-n:0/15203791-n:0/15204297-n:0/15273626-n:0
```

Agora como apresentar para os revisores estas opções e colher o feedback deles de forma mais automática possível? Uma idéia seria criar um questionário usando algum destes sistemas tipo SurveyMonkey ou LimeSurvey etc. Neste último, existe um tipo de questão que aceita mais de uma resposta com comentários. Outros sistemas tem suporte melhor? Acho que não

Mas o chato é que os códigos de synsets deveriam ser links para nossa interface para faciltiar a revisão. Alternativamente, podemos pensar em desenvolver um sistema simples para recolher estes feedbacks. Produziríamos páginas HTML anotadas com botões de concordo/discordo e espaço para alternativa.  Isto daria um certo trabalho, mais garantiria maior eficiência dos anotadores.

![test](https://cloud.githubusercontent.com/assets/86403/7163264/74a7463c-e36f-11e4-98f4-a8af3ca58632.png)

Enfim, temos que pensar como fazer a pesquisa e tabular os resultados...

**Comment by fcbr** [comment]
implementado.  http://logics.emap.fgv.br/wn/sense-tagging-frame

**Comment by vcvpaiva** [comment]
Alexandre, o problema maior com essa ideia e' que voce teria que saber
fazer o WSD e o seu exemplo me parece errado. veja so':
1. 03408721-n http://logics.emap.fgv.br/wn/synset?id=03408721-n future *
   | futuro *
   - _bulk commodities bought or sold at an agreed price for delivery at
     a specified future date_
2. 06330401-n http://logics.emap.fgv.br/wn/synset?id=06330401-n
   future_tense, future \* | futuro *
   - _a verb tense that expresses actions or states in the future_
3. 15121625-n http://logics.emap.fgv.br/wn/synset?id=15121625-n
   hereafter, future, time_to_come, futurity \* | vindouro, futuro *
   - _the time yet to come_

voce escolheu o primeiro senso de futuro que eu acho que esta' claramente
errado pra sentenca. pode ser que eles estejam falando de "futuro" no
sentido economico da palavra (commodities), mas se o texto for jornalistico
'e muito mais provavel que o senso seja o terceiro, o porvir.

os exemplos do Fabricio em http://logics.emap.fgv.br/wn/sense-tagging-frame
mostram bem as difficuldades desse approach naive demais:
vale
http://logics.emap.fgv.br/wn/sense-tagging-details?file=bosque.json&text=1&word=10&userid=fabricio
no texto 2 nao 'e substantivo, nem e' noite
http://logics.emap.fgv.br/wn/sense-tagging-details?file=bosque.json&text=3&word=15&userid=fabricio,
que devia ser "a noite"=adverbio temporal. no texto 5, clinicas nao foi
reconhecido como substantivo
e eu duvido muito que voce consiga algum aluno/turk que possa lidar com a
quantidade de sinonimos pra e.g. mulher.
my two cents.

On Tue, Apr 28, 2015 at 7:38 AM, Fabricio Rosario notifications@github.com
wrote:

> Closed #56 https://github.com/fcbr/cl-wnbrowser/issues/56.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/56#event-292041073.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/

**Comment by vcvpaiva** [comment]
nice implementation, by the way, Fabricio.

2015-04-28 8:13 GMT-07:00 Valeria de Paiva valeria.depaiva@gmail.com:

> Alexandre, o problema maior com essa ideia e' que voce teria que saber
> fazer o WSD e o seu exemplo me parece errado. veja so':
> 1. 03408721-n http://logics.emap.fgv.br/wn/synset?id=03408721-n
>    future \* | futuro *
>    - _bulk commodities bought or sold at an agreed price for delivery
>      at a specified future date_
> 2. 06330401-n http://logics.emap.fgv.br/wn/synset?id=06330401-n
>    future_tense, future \* | futuro *
>    - _a verb tense that expresses actions or states in the future_
> 3. 15121625-n http://logics.emap.fgv.br/wn/synset?id=15121625-n
>    hereafter, future, time_to_come, futurity \* | vindouro, futuro *
>    - _the time yet to come_
> 
> voce escolheu o primeiro senso de futuro que eu acho que esta' claramente
> errado pra sentenca. pode ser que eles estejam falando de "futuro" no
> sentido economico da palavra (commodities), mas se o texto for jornalistico
> 'e muito mais provavel que o senso seja o terceiro, o porvir.
> 
> os exemplos do Fabricio em
> http://logics.emap.fgv.br/wn/sense-tagging-frame mostram bem as
> difficuldades desse approach naive demais:
> vale
> http://logics.emap.fgv.br/wn/sense-tagging-details?file=bosque.json&text=1&word=10&userid=fabricio
> no texto 2 nao 'e substantivo, nem e' noite
> http://logics.emap.fgv.br/wn/sense-tagging-details?file=bosque.json&text=3&word=15&userid=fabricio,
> que devia ser "a noite"=adverbio temporal. no texto 5, clinicas nao foi
> reconhecido como substantivo
> e eu duvido muito que voce consiga algum aluno/turk que possa lidar com a
> quantidade de sinonimos pra e.g. mulher.
> my two cents.
> 
> On Tue, Apr 28, 2015 at 7:38 AM, Fabricio Rosario <
> notifications@github.com> wrote:
> 
> > Closed #56 https://github.com/fcbr/cl-wnbrowser/issues/56.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/fcbr/cl-wnbrowser/issues/56#event-292041073.
> 
> ## 
> 
> Valeria de Paiva
> http://www.cs.bham.ac.uk/~vdp/
> http://valeriadepaiva.org/

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/
