### ISSUE TITLE
$hashtags e @userid para menções e marcar synsets

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#58]
Pena que quando
busco por um synset muito específico (especialmente significados que
eu nunca ouvi falar) nem o linguee nem as outras wordnets têm me
ajudado a achar um equivalente, como em
http://logics.emap.fgv.br/wn/synset?id=04119892-n

Acho que vale fazer um comentário neste synset, já pedi ao Chalub para pensarmos em tags que nos ajudem a marcar os synsets. Este poderia receber algo como #dificil  para nos chamar atenção para verificação futura.

**Comment by fcbr** [comment]
incorporei o seu comentario no issue #35

**Comment by vcvpaiva** [comment]
a ideia de marcar alguns synsets como "dificeis" me parece interessante,
mas esse exemplo em particular e' uma bobagem, nao vale a pena pensar nele.

On Thu, Apr 16, 2015 at 3:09 AM, Fabricio Rosario notifications@github.com
wrote:

> incorporei o seu comentario no issue #35
> https://github.com/fcbr/cl-wnbrowser/issues/35
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/58#issuecomment-93699246.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/

**Comment by arademaker** [comment]
pode ser uma bobagem se considerarmos a usabilidade, mas é bem representativo sobre o tipo de situação que ocorre em muitos casos...

**Comment by vcvpaiva** [comment]
nao acho nao. o exemplo de snarl/snap 'e muito mais representativo. o
exemplo da Livy e' (na minha parca avaliacao dos dados) um "outlier".  mas
mesmo a nocao de #dificil nao 'e so' uma nao, tem varias.

2015-04-16 8:07 GMT-07:00 Alexandre Rademaker notifications@github.com:

> pode ser uma bobagem se considerarmos a usabilidade, mas é bem
> representativo sobre o tipo de situação que ocorre em muitos casos...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/58#issuecomment-93758230.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/
