### ISSUE TITLE
zero-downtime durante deploy?

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#59]
emos que estudar como fazer zero-downtime deployment no bluemix

**Comment by fcbr** [comment]
Temos que nos certificar que o manifest.yml esta' com a referencia correta para o Cloudant.  Basta usar o CF da seguinte maneira:

cf rename app app_old
cf push
cf stop app_old

**Comment by arademaker** [comment]
isto tem que ficar em algum README ou doc de fácil acesso...
