### ISSUE TITLE
busca por partes de palavras (sufixos ou prefixos)

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#6]
Quando busca por 'corre' poderia vir correr, corredura, todos as palavras que têm "corre". Por exemplo, como no AC/DC da Linguateca:

http://www.linguateca.pt/acesso/corpus.php?corpus=OBRAS

**Comment by fcbr** [comment]
O SOLR permite fazer isso usando asteriscos.  Por exemplo:

http://logics.emap.fgv.br/wn/search?term=crema*&start=0

Talvez seja interessante criar um help descrevendo a sintaxe usada pelo SOLR.

**Comment by arademaker** [comment]
O chato é que para pesquisar as nominalizações, precisamos fazer outra query:

http://logics.emap.fgv.br/wn/search?term=nomlex_noun%3A*ura

Isto ocorre porque nosso índice tem 2 tipos de documentos, com campos diferentes. As nominalizações tem os campos nomlex_noun e nomlex_verb e os synsets nos campos word_en, word_br, gloss_en, gloss_br, text (que é uma cópia de todos os outros campos de synset e campo default de busca). 

Além disso, os usuários não tem como advinhar os campos dos documentos. Talvez a interface pudesse expor, de alguma forma, os campos possíveis para busca. Só para deixar registrado. Mas o issue pode realmente ser fechado.

**Comment by fcbr** [comment]
Acho que vale abrir uma issue mais especifica entao, com propostas
de UI, etc.
