### ISSUE TITLE
search gives priority to word in synset

### ISSUE THREAD

**Issue by vcvpaiva** [fcbr/cl-wnbrowser#61]
IT would make my life much easier if I could distinguish when a word is in the synset itself or it's used as a gloss or definition or a exemple in  synset. For example: if I search for "see" and verb-synset, I get 17 results, of these 8 have the word "see" in the synset, the other 9 only have "see" in the examples or the definition. but the 8 synsets where "see" is very important don't show up first, which is distracting and confusing. for "see" it's not too bad, as the result set is small; for "provide"  I get 282 entries to check, where provide is mostly used in the definition.

this is a request fro improvement, not a bug.

**Comment by arademaker** [comment]
Já falamos e escrevemos sobre isso. Vc pode limitar o campo de busca com a sintaxe:

FIELD:VALUE

Mas parece haver mesmo um bug. Chalub, buscas no campo word_pt funcionam:

http://logics.emap.fgv.br/wn/search?term=word_pt%3Acomprar

Mas buscas no campo word_en não?! Os nomes dos campos precisam ser colocados em algum lugar para os usuários saberem que podem usar. Talvez uns exemplos de consultas ajudem...

**Comment by fcbr** [comment]
Added word_en to the search index in Cloudant (http://logics.emap.fgv.br/wn/search?term=word_en%3Abug).  No changes to code necessary.

Since we already have a request for the other issue (issue #45), I'm closing this as fixed.

**Comment by arademaker** [comment]
Mas precisamos documentar os campos que os usuários podem usar..

Sent from my iPhone
