### ISSUE TITLE
Morphosemantic Database

### ISSUE THREAD

**Issue by fcbr** [fcbr/cl-wnbrowser#68]
per @vcvpaiva's request.

add morphosemantic relations, described here https://wordnet.princeton.edu/wordnet/download/standoff/

copy/paste:

Morphosemantic Database

Links among noun and verb synsets containing words that share an underlying meaning and are derivationally related. The morphosemantic database (semantic relations between morphologically related nouns and verbs) for WordNet3.0 contains derivational links connecting noun and verb senses, e.g., employment#n1-employ#v2. morphosemantic-links.xls repeats these links, but also give the semantic type of the relationship. The database uses 14 semantic relations, as listed in the README file, and can be downloaded from http://wordnetcode.princeton.edu/standoff-files/morphosemantic-links.xls.

**Comment by arademaker** [comment]
Please, let us talk first!

**Comment by fcbr** [comment]
will merge with #28
