### ISSUE TITLE
unir entradas da Cláudia

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#69]
Podemos unir os comentários e sugestões da claudia em um usuário apenas?

(maclaudia.freitas), claudiafreitas e claufreitas

**Comment by arademaker** [comment]
usar @claudiafreitas como usuário final.

**Comment by arademaker** [comment]
Curioso como vc fez isso. Pode documentar?

**Comment by fcbr** [comment]
veja arquivo utils/update-user.js no JAZZ (ownpt2)
