### ISSUE TITLE
bug navegação multi-aba

### ISSUE THREAD

**Issue by livyreal** [fcbr/cl-wnbrowser#71]
oi meninos,

quando eu estou com dois synsets abertos do navegador e arrumo/sugiro/voto em um deles, as duas páginas abertas são atualizadas para o synset que atualizei por último. Assim, não é possível navegar em dois synsets, em duas tabs diferentes, ao mesmo tempo.

**Comment by arademaker** [comment]
tb tenho este problema no meu telefone.

**Comment by livyreal** [comment]
estou usando win, google chrome. acabei de passar a usar firefox para ver se melhora.
