### ISSUE TITLE
List suggestions only to those logged in

### ISSUE THREAD

**Issue by livyreal** [fcbr/cl-wnbrowser#74]
meninos, é possível que as discussões de glosa/add-word, etc sejam visíveis apenas para pessoas conectadas?
tenho a impressão que antes esta info não era visível e agora é.

**Comment by fcbr** [comment]
A lista de sugestoes sempre foi visible, mas as opcoes de add/remove/etc sao visiveis apenas para quem esta logado, veja um exemplo abaixo (estou deslogado):

![issue-74](https://cloud.githubusercontent.com/assets/600594/7356093/651ff808-ecfc-11e4-8fde-4303c0b2b3a8.png)

**Comment by livyreal** [comment]
e não dá para mudar isto, será? acho estranho os synsets que ainda estão sendo preparados ficarem expostos a toda web...

**Comment by fcbr** [comment]
ah entendi, bom vou reabrir e deixar a sugestao de enhancement.

**Comment by vcvpaiva** [comment]
Livy,
eu acho que 'e pra ser assim mesmo. os synsets que estao sendo melhorados
ficam expostos a  toda web.
isso nao 'e bug, 'e design decision, me parece e eu acho bom.

Valeria

On Mon, Apr 27, 2015 at 12:48 PM, Livy Real notifications@github.com
wrote:

> e não dá para mudar isto, será? acho estranho os synsets que ainda estão
> sendo preparados ficarem expostos a toda web...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/74#issuecomment-96795031.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/

**Comment by livyreal** [comment]
ok, eu não acho bom, mas tanto faz, na verdade.

**Comment by arademaker** [comment]
Fui eu quem pediu ao Chalub para deixar as sugestões e comentários abertos.
Nosso sistema é bem aberto mesmo, qualquer pessoa autenticada no github
pode comentar e sugerir. Apenas a aprovação de sugestões é mais controlada.
Por isso não vejo grandes razões para manter estes dados protegidos não.
Acho até bom para as pessoas saberem como alguns casos geram discussões.
Enfim, se aparecer um BOM argumento para fecharmos, tudo bem, caso
contrário, sugiro manter assim por enquanto.

Ab.,

**Comment by vcvpaiva** [comment]
hmm, pessoas nao ligadas a nos, podem ver sugestoes e ate opinar, certo? o
que elas nao podem fazer 'e votar. me parece bom. e parece melhor do que
deixar alguns absurdos que temos sem mostrar que estamos trabalhando pra
melhorar. e se so' mostrarmos o que verificamos, nao sobra nada.

2015-04-27 13:35 GMT-07:00 Livy Real notifications@github.com:

> ok, eu não acho bom, mas tanto faz, na verdade.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/74#issuecomment-96811987.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/

**Comment by arademaker** [comment]
Votar é uma questão interessante. Acho que logados podem votar também, só
não podem aprovar a sugestão. Bem, talvez votar tenha que ser restrito ao
grupo mesmo. Vou abrir outro issue para isso.

Alexandre Rademaker
http://arademaker.github.com/

**Comment by vcvpaiva** [comment]
eu nao sei quem foi o icerqueira, mas um icerqueira comentou na no
significado de "storm" como chover era fraco demais.
acho que ter o input de estranhos e' bem legal e util.

2015-04-27 13:44 GMT-07:00 Alexandre Rademaker notifications@github.com:

> Votar é uma questão interessante. Acho que logados podem votar também, só
> não podem aprovar a sugestão. Bem, talvez votar tenha que ser restrito ao
> grupo mesmo. Vou abrir outro issue para isso.
> 
> Alexandre Rademaker
> http://arademaker.github.com/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/74#issuecomment-96814493.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/
