### ISSUE TITLE
quero aprovar glosas =)

### ISSUE THREAD

**Issue by livyreal** [fcbr/cl-wnbrowser#76]
quero poder aprovar glosas. quero no mínimo poder rejeitar glosas sem mais ninguém precisar revisar. e, se vcs quiserem, acho que vcs poderiam ter este "poder" também. as glosas têm, em geral, uma qualidade ruim e reprovar é fácil (às vezes, aprovar é que é difícil!)

**Comment by arademaker** [comment]
isto não é bug nem pedido de alteração no sistema, apenas sugestão de novos parâmetros de configuração.
