### ISSUE TITLE
WildcardQuery do Cloudant não permite * no início do valor

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#78]
http://logics.emap.fgv.br/wn/search?term=*ora

Parece bug no cloudant que precisa ser reportado.

**Comment by fcbr** [comment]
Cloudant support case 46579.

**Comment by fcbr** [comment]
This is the support case that was opened:

"If we attempt to search for something like "*foo" we get the following response from Cloudant:

Cannot parse '*foo': '*' or '?' not allowed as first character in WildcardQuery

It seems that this is a limitation of Lucene and the SetAllowLeadingWildcard enables this functionality.  Is it possible to have this option on Cloudant as well?"

**Comment by arademaker** [comment]
@vcvpaiva disse "Alexandre eu so' queria mesmo palavras em ingles que terminassem em ize e fossem verbos."

**Comment by arademaker** [comment]
@fcbr estranho quem disse ser uma limitação do Lucene, no SOLR funciona e o SOLR é só um wrapper do Lucene.

**Comment by fcbr** [comment]
Reply from support: "It is not possible to set that option in Cloudant. I apologize for any inconvenience caused by this."

**Comment by fcbr** [comment]
Isso foi indiretamente consertado na versao SOLR.
