### ISSUE TITLE
facet search

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#8]
A forma de usar as facetas tem suas particularidades. Por exemplo, se pesquiso por "casa" e depois refino a busca escolhendo um valor específico de uma faceta, por exemplo, clicando em verb.change para o campo  wn30_lexicographerFile, a query não deveria mudar, apenas um filtro adicional ser adicionado. SOLR implementa isso com o campo fq (facet query). Ou seja, vc não muda sua query inicial, apenas acrescenta filtros a medida que escolhe um valor de uma faceta. 

Outra coisa importante é permitir que estes filtros adicionados a uma query possam ser removidos e/ou trocados por outros. 

http://wiki.apache.org/solr/CommonQueryParameters#fq

Veja, por exemplo, o comportamento de 

http://dblp.l3s.de/?q=rademaker&search_opt=all&newQuery=yes&resTableName=query_resultZIx44V&synt_query_exp=full

Eu posso adiconar ou remover a restrição dos anos sem mudar a query principal, "rademaker". Por isso estas facetas são geralmente colocadas em barras ao lado dos resultados.

**Comment by fcbr** [comment]
Mudei para usar filter query (fq) ao inves de term para filtrar por facet o que simplificou o codigo e a URL, mas ainda precisamos discutir a usabilidade de multiplos filtros.

**Comment by fcbr** [comment]
Isso foi implementado ha' um tempo.  Esqueci de fechar.
