### ISSUE TITLE
couting votes

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#83]
http://logics.emap.fgv.br/wn/synset?id=07691863-n

cadastrei  e resolvi tirar meu voto pela minha insegurança de algo que na realidade só estou cadastrando pela @vcvpaiva. Mas os votos ficaram somando -1 ao invés de zero!?

**Comment by fcbr** [comment]
a votacao funciona similar ao reddit: usuarios podem votar pra "cima" ou para "baixo", ou remover o voto.

tambem similar ao reddit, para remover o voto, basta clicar novamente na seta previamente utilizada. por exemplo, para remover um voto para "cima", voce deve clicar na seta para cima novamente. ela mudara' de cor para cinza.

me parece que voce trocou o seu voto de "cima" para "baixo", dai' o resultado -1.

para zerar a sua votacao, retire o seu voto para "baixo" clicando na seta para baixo novamente.

http://www.reddit.com/wiki/voting
