### ISSUE TITLE
Interface anotação de textos: anotador precisa ver as decisões feitas e editar?

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#84]
Claudia reportou: Ainda nao terminei - demora e estou na metade -, mas queria saber como eu poderei ver os meus resultados - quantos missing, quantos problemas de lema, etc

**Comment by ghost** [comment]
sim, deve ser possível corrigir erros. Acabo de perceber que cometi uns 2, e seria bom poder consertar.

**Comment by fcbr** [comment]
Duplicado em relacao `a issue #99
