### ISSUE TITLE
remover sugestões repetidas.

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#87]
dando continuidade ao issue #53 agora precisamos limpar o BD das sugestões repetidas. O arquivo do Hugo parece conter várias e também podem ter existido outras cadastradas manualmente ou criadas manualmente mas que já constavam como sugestões do arquivo do Hugo. 

Enfim, precisamos limpar as repetições preservando a mais antiga e removendo a sugestão mais recente. Se isto não for feito, teremos distorções nas estatísticas.

**Comment by fcbr** [comment]
Feito diretamente em logics.emap.fgv.br.  Os seguintes synsets foram corrigidos: 00024264-n 00024720-n 00027167-n 00032733-a 00069879-v 00102201-a
00106921-r 00155869-v 00172710-n 00193799-a 00249721-a 00262792-a
00352826-v 00364881-a 00484166-v 00489108-a 00566342-a 00579712-v
00582388-n 00583246-n 00584367-n 00595299-a 00602112-v 00606335-v
00606370-n 00641944-a 00645415-v 00648224-v 00653283-v 00668099-v
00677445-v 00714718-v 00715074-v 00752764-v 00758525-n 00794079-v
00802946-v 00848466-a 00849357-a 00870577-v 00871942-v 00906037-v
00917772-v 00963896-n 00968211-v 01020885-a 01170962-n 01185611-n
01212572-v 01263013-a 01443097-a 01672607-a 01676517-a 01730059-v
01765392-v 01789514-v 01802165-a 01804175-a 01821884-v 01935476-v
01950198-a 02077656-v 02144835-v 02145429-v 02147109-v 02154312-v
02207206-v 02210855-v 02238085-v 02288295-v 02407338-v 02435311-v
02442205-v 02451370-v 02472223-v 02526085-v 02547586-v 02609764-v
02629793-v 02756098-n 02959942-n 03051540-n 03064758-n 03169390-n
03183080-n 03234306-n 03544360-n 04076846-n 04159058-n 04295881-n
04679419-n 04679549-n 04683814-n 04802907-n 04893525-n 04933544-n
04945530-n 05034225-n 05074774-n 05091194-n 05093581-n 05098942-n
05155821-n 05157574-n 05159225-n 05526713-n 05600637-n 05601357-n
05622456-n 05799212-n 05833840-n 05835747-n 05837957-n 05845332-n
05898568-n 05941423-n 05982152-n 06652242-n 06762711-n 06778102-n
06806469-n 07152948-n 07153130-n 07153838-n 07175241-n 07175575-n
07176804-n 07180787-n 07181935-n 07270179-n 07286368-n 07314838-n
07495327-n 07503260-n 07503430-n 07535010-n 07535670-n 07739125-n
07951464-n 07961480-n 08049401-n 08184217-n 08415774-n 08507558-n
08616311-n 08622950-n 08679972-n 08685677-n 09258715-n 09334396-n
09360122-n 09433442-n 09727627-n 10014939-n 10536728-n 10663315-n
13289159-n 13295657-n 13480848-n 13903079-n 13945919-n 13963970-n
13969243-n 13976322-n 14449405-n 14854847-n 15113229-n 15122231-n
15239292-n 15266911-n
