### ISSUE TITLE
add limit to search

### ISSUE THREAD

**Issue by fcbr** [fcbr/cl-wnbrowser#89]
add limit to search so that user can customize the default 10 entries per page.

**Comment by fcbr** [comment]
Added "limit" parameter.  Usage example:

http://logics.emap.fgv.br/wn/search?term=sea&limit=200

Maximum value is 200 (Cloudant limitation).

**Comment by vcvpaiva** [comment]
thanks!

On Tue, May 5, 2015 at 4:50 AM, Fabricio Rosario notifications@github.com
wrote:

> Added "limit" parameter. Usage example:
> 
> http://logics.emap.fgv.br/wn/search?term=sea&limit=200
> 
> Maximum value is 200 (Cloudant limitation).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/89#issuecomment-99057385.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/

**Comment by vcvpaiva** [comment]
mas nao funciona!
 Error

The search for '_:_&limit=200' resulted in the following error:
- _Cannot parse '_:_&limit=200': '_' or '?' not allowed as first
  character in WildcardQuery*

_com espaco *:_& limit=200*

o limite nao pega, continua indo de 10 em 10.

On Tue, May 5, 2015 at 6:09 AM, Valeria de Paiva valeria.depaiva@gmail.com
wrote:

> thanks!
> 
> On Tue, May 5, 2015 at 4:50 AM, Fabricio Rosario <notifications@github.com
> 
> > wrote:
> > 
> > Added "limit" parameter. Usage example:
> > 
> > http://logics.emap.fgv.br/wn/search?term=sea&limit=200
> > 
> > Maximum value is 200 (Cloudant limitation).
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/fcbr/cl-wnbrowser/issues/89#issuecomment-99057385.
> 
> ## 
> 
> Valeria de Paiva
> http://www.cs.bham.ac.uk/~vdp/
> http://valeriadepaiva.org/

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/

**Comment by arademaker** [comment]
@vcvpaiva , veja o exemplo do Chalub:

http://logics.emap.fgv.br/wn/search?term=sea&limit=200

`limit` é um parâmetro de url, não para ser colocado dentro da caixa de busca. O valor colocando dentro da caixa de busca vira o valor do parâmetro de url `term`.

Sua url ficou:
http://logics.emap.fgv.br/wn/search?term=*%3A*%26limit

A que ele sugeriu foi:
http://logics.emap.fgv.br/wn/search?term=*%3A*&limit=100

Entendeu a diferença? No momento, não temos nenhum controle ou link na interface para colocar este parâmetro na url, vc precisa editar a url na mão e adicionar este parâmetro.

term = _%3A_
limit = 100

onde %3A são os dois pontos codificados.
