### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#9]
Some initial doc about instalation of the tool, solr, proxy etc.

**Comment by fcbr** [comment]
The README already contains this, although it is somewhat terse and could be improved.  The crucial part is the triple store -> SOLR document creation, which is external to this project and should probably be registered as an issue in the correct repo.

**Comment by arademaker** [comment]
I was thinking about merging the repos. What do you think? The repo https://github.com/arademaker/wordnet-editor is obsolete now but it still contains some code used for solr creation...

**Comment by fcbr** [comment]
I don't mind.
