### ISSUE TITLE
valor default de busca não se altera

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#90]
fiz uma busca por uma expressão regular de buscas subsequentes por ID de synset não alteraram o valor da busca inicial.

**Comment by fcbr** [comment]
Nao entendi.

**Comment by arademaker** [comment]
na home, busca por "house". escolhe um synset qualquer, navega para algum outro ligado à ele, copia um código de synset qq e coloca na busca. Quando vc fizer a busca vc vai para o synset do código e a caixa de busca volta a mostrar "house". Não é necessariamente um problema, mas é curioso.
