### ISSUE TITLE
busca regex e wildcard não funciona

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#91]
sensualizar-se e sensualizar. No segundo caso não retorna nada.  Busca por /sensualizar(-se)?/ como regex deveria retornar casos com e sem -se. 

```
urca:Downloads arademaker$ cat teste.text
sensualizar-se
sensualizar
outra coisa
urca:Downloads arademaker$ egrep "sensualizar(-se)?" teste.text
sensualizar-se
sensualizar
urca:Downloads arademaker$ egrep "sensualizar" teste.text
sensualizar-se
sensualizar
urca:Downloads arademaker$ egrep "sensualizar-se" teste.text
sensualizar-se
```

**Comment by fcbr** [comment]
Isso foi indiretamente consertado usando a versao SOLR do sistema.  SOLR tutorial sobre regexes: http://www.openjems.com/solr-regex-tutorial/

**Comment by vcvpaiva** [comment]
Hmm, ainda estamos tendo problemas com busca:
se voces tentarem "air conditioning" vao ver que temos
684 results found for 'air conditioned' e684 results found for 'air
conditioning'

mas o que eu quero 'e
1. 02686379-n http://logics.emap.fgv.br/wn/synset?id=02686379-n
   air_conditioning, air_conditioner \* | ar condicionado, condicionador de
   ar, condicionamento de ar, ar-condicionado *
   - _a system that keeps air cool and dry_

e nao sei se tem um jeito de pedir o underscore.

Valeria

On Wed, May 13, 2015 at 5:00 PM, Fabricio Rosario notifications@github.com
wrote:

> Closed #91 https://github.com/fcbr/cl-wnbrowser/issues/91.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/91#event-304422840.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/

**Comment by arademaker** [comment]
Em qual interface vc está tentando? prod ou des? Me passa um exemplo da query? Se vc estiver usando entre aspas, a busca é literal.

**Comment by vcvpaiva** [comment]
production
http://logics.emap.fgv.br/wn/search?term=air+conditioning

2015-05-13 18:19 GMT-07:00 Alexandre Rademaker notifications@github.com:

> Em qual interface vc está tentando? prod ou des? Me passa um exemplo da
> query? Se vc estiver usando entre aspas, a busca é literal.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/91#issuecomment-101873800.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/

**Comment by fcbr** [comment]
Infelizmente, a busca regex so' funciona na versao SOLR, conforme
comentario acima.

On Wed, May 13, 2015, at 10:42 PM, Valeria de Paiva wrote:

> production
> 
> http://logics.emap.fgv.br/wn/search?term=air+conditioning
> 
> 2015-05-13 18:19 GMT-07:00 Alexandre Rademaker
> notifications@github.com:
> 
> Em qual interface vc está tentando? prod ou des? Me passa um
> exemplo da
> 
> query? Se vc estiver usando entre aspas, a busca é literal.
> 
> —
> 
> Reply to this email directly or view it on GitHub
> 
> https://github.com/fcbr/cl-wnbrowser/issues/91#issuecomment-101873800.
> 
> ## 
> 
> Valeria de Paiva
> 
> http://www.cs.bham.ac.uk/~vdp/
> 
> http://valeriadepaiva.org/
> — Reply to this email directly or view it on GitHub[1].

Links:
1. https://github.com/fcbr/cl-wnbrowser/issues/91#issuecomment-101876855

**Comment by vcvpaiva** [comment]
ok, entendi agora, obrigada.

2015-05-14 3:24 GMT-07:00 Fabricio Rosario notifications@github.com:

> Infelizmente, a busca regex so' funciona na versao SOLR, conforme
> comentario acima.
> 
> On Wed, May 13, 2015, at 10:42 PM, Valeria de Paiva wrote:
> 
> > production
> > 
> > http://logics.emap.fgv.br/wn/search?term=air+conditioning
> > 
> > 2015-05-13 18:19 GMT-07:00 Alexandre Rademaker
> > notifications@github.com:
> > 
> > Em qual interface vc está tentando? prod ou des? Me passa um
> > exemplo da
> > 
> > query? Se vc estiver usando entre aspas, a busca é literal.
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/fcbr/cl-wnbrowser/issues/91#issuecomment-101873800.
> > 
> > ## 
> > 
> > Valeria de Paiva
> > 
> > http://www.cs.bham.ac.uk/~vdp/
> > 
> > http://valeriadepaiva.org/
> > — Reply to this email directly or view it on GitHub[1].
> 
> Links:
> 1. https://github.com/fcbr/cl-wnbrowser/issues/91#issuecomment-101876855
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/91#issuecomment-101995922.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/
