### ISSUE TITLE
stats da interface não está funcionando

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#94]
com a troca do BD, temos que repensar na página stats. Acredito que esta relacionado a https://github.com/arademaker/openWordnet-PT/issues/36 se formos manter um SPARQL endpoint atualizado.

**Comment by fcbr** [comment]
Isto e' muito mais facil com SOLR; estou implementando agora.

**Comment by fcbr** [comment]
Fixed na versao SOLR.
