### ISSUE TITLE
abrir dois synsets de uma vez no navegador

### ISSUE THREAD

**Issue by livyreal** [fcbr/cl-wnbrowser#95]
oi meninos, parece que este erro voltou. Quando abro mais de um synset, de repente, todos são atualizados para o último aberto.

**Comment by arademaker** [comment]
Te ocorre comigo

**Comment by fcbr** [comment]
E' o mesmo que #62 ?

EDIT: se nao for, tem como definir os passos para reproduzir?

**Comment by livyreal** [comment]
é este sim!

**Comment by fcbr** [comment]
ok, vou fechar como duplicado.  consertar o #62 esta' sendo mais complexo do que eu imaginava pois tenho que alterar a forma de autenticacao que estamos fazendo via OAUTH.
